
# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_can QUIET)
else()
    find_package(mts_can)
endif()

if (NOT (mts_can_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_can failed: ${mts_can_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_ecu QUIET)
else()
    find_package(mts_ecu)
endif()

if (NOT (mts_ecu_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_ecu failed: ${mts_ecu_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_eth QUIET)
else()
    find_package(mts_eth)
endif()

if (NOT (mts_eth_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_eth failed: ${mts_eth_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_flexray QUIET)
else()
    find_package(mts_flexray)
endif()

if (NOT (mts_flexray_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_flexray failed: ${mts_flexray_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_gps QUIET)
else()
    find_package(mts_gps)
endif()

if (NOT (mts_gps_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_gps failed: ${mts_gps_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_ref_cam QUIET)
else()
    find_package(mts_ref_cam)
endif()

if (NOT (mts_ref_cam_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_ref_cam failed: ${mts_ref_cam_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_rt_range QUIET)
else()
    find_package(mts_rt_range)
endif()

if (NOT (mts_rt_range_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_rt_range failed: ${mts_rt_range_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mtscpp QUIET)
else()
    find_package(mtscpp)
endif()

if (NOT (mtscpp_FOUND))

    # depending package cannot be imported
    set(next_UDEX_COMPONENT_FOUND 0)
    set(
        next_UDEX_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mtscpp failed: ${mtscpp_NOT_FOUND_MESSAGE}"
    )
endif()

