
# Generated file; Do not edit!
# Generated by D:/.bbs_conan/da1d67082205e/1/cmake/pre/scripts/tagged_paths_json_to_cmake.py
#
# This file is for Bricks core internal use only and thus
# DO NOT USE OUTSIDE BRICKS CORE!

# This file lists paths to external libraries
# which our current package uses


# we have not yet defined variable
# for tag all, we shall make one
if (NOT DEFINED BRICKS_LABEL_ALL_PATH)
    set(BRICKS_LABEL_ALL_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_ALL_PATH
    "D:/.bbs_conan/06ba7cd/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/a4b0521/1"  # asio.generic
    "D:/.bbs_conan/ec0e6d9f10cb3/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/da1d67082205e/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/3f54ddd49/1"  # bricks_cmake_groups.__system
    "D:/.bbs_conan/2dbadcf/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/6bdf8e/1"  # cip_build_system_platforms.__system
    "D:/.bbs_conan/85e48f2e4ee1e/1"  # cmake
    "D:/.bbs_conan/0d0c747/1"  # ecal.measurement
    "D:/.bbs_conan/5238187/1"  # flatbuffers
    "D:/.bbs_conan/2a40d25/1"  # hdf5.generic
    "D:/.bbs_conan/f529bc3/1"  # jsoncpp.generic
    "D:/.bbs_conan/e0bc3ee2/1"  # make
    "D:/.bbs_conan/7b93f5/1"  # mts-core-lib
    "D:/.bbs_conan/dbe9207ff6ddb/1"  # mts-sentinel
    "D:/.bbs_conan/86183a9/1"  # opencv.generic
    "D:/.bbs_conan/a9d6a69/1"  # protobuf
    "D:/.bbs_conan/5502851/1"  # recycle.generic
    "D:/.bbs_conan/1c5bcfd/1"  # simpleini.generic
    "D:/.bbs_conan/4e258c5/1"  # spdlog.generic
    "D:/.bbs_conan/54693d2/1"  # tclap.generic
    "D:/.bbs_conan/8c7a410/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/0f0c763c7b9/1"  # tracy
)

# we have not yet defined variable
# for tag build, we shall make one
if (NOT DEFINED BRICKS_LABEL_BUILD_PATH)
    set(BRICKS_LABEL_BUILD_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_BUILD_PATH
    "D:/.bbs_conan/06ba7cd/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/ec0e6d9f10cb3/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/da1d67082205e/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/3f54ddd49/1"  # bricks_cmake_groups.__system
    "D:/.bbs_conan/2dbadcf/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/6bdf8e/1"  # cip_build_system_platforms.__system
    "D:/.bbs_conan/85e48f2e4ee1e/1"  # cmake
    "D:/.bbs_conan/5238187/1"  # flatbuffers
    "D:/.bbs_conan/f529bc3/1"  # jsoncpp.generic
    "D:/.bbs_conan/e0bc3ee2/1"  # make
    "D:/.bbs_conan/86183a9/1"  # opencv.generic
    "D:/.bbs_conan/a9d6a69/1"  # protobuf
)

# we have not yet defined variable
# for tag deploy, we shall make one
if (NOT DEFINED BRICKS_LABEL_DEPLOY_PATH)
    set(BRICKS_LABEL_DEPLOY_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_DEPLOY_PATH
    "D:/.bbs_conan/a4b0521/1"  # asio.generic
    "D:/.bbs_conan/0d0c747/1"  # ecal.measurement
    "D:/.bbs_conan/2a40d25/1"  # hdf5.generic
    "D:/.bbs_conan/7b93f5/1"  # mts-core-lib
    "D:/.bbs_conan/dbe9207ff6ddb/1"  # mts-sentinel
    "D:/.bbs_conan/5502851/1"  # recycle.generic
    "D:/.bbs_conan/1c5bcfd/1"  # simpleini.generic
    "D:/.bbs_conan/4e258c5/1"  # spdlog.generic
    "D:/.bbs_conan/54693d2/1"  # tclap.generic
    "D:/.bbs_conan/8c7a410/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/0f0c763c7b9/1"  # tracy
)

# we have not yet defined variable
# for tag platform, we shall make one
if (NOT DEFINED BRICKS_LABEL_PLATFORM_PATH)
    set(BRICKS_LABEL_PLATFORM_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_PLATFORM_PATH
    "D:/.bbs_conan/6bdf8e/1"  # cip_build_system_platforms.__system
)

# we have not yet defined variable
# for tag production, we shall make one
if (NOT DEFINED BRICKS_LABEL_PRODUCTION_PATH)
    set(BRICKS_LABEL_PRODUCTION_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_PRODUCTION_PATH
    "D:/.bbs_conan/06ba7cd/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/a4b0521/1"  # asio.generic
    "D:/.bbs_conan/2dbadcf/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/85e48f2e4ee1e/1"  # cmake
    "D:/.bbs_conan/0d0c747/1"  # ecal.measurement
    "D:/.bbs_conan/5238187/1"  # flatbuffers
    "D:/.bbs_conan/2a40d25/1"  # hdf5.generic
    "D:/.bbs_conan/f529bc3/1"  # jsoncpp.generic
    "D:/.bbs_conan/e0bc3ee2/1"  # make
    "D:/.bbs_conan/7b93f5/1"  # mts-core-lib
    "D:/.bbs_conan/dbe9207ff6ddb/1"  # mts-sentinel
    "D:/.bbs_conan/86183a9/1"  # opencv.generic
    "D:/.bbs_conan/a9d6a69/1"  # protobuf
    "D:/.bbs_conan/5502851/1"  # recycle.generic
    "D:/.bbs_conan/1c5bcfd/1"  # simpleini.generic
    "D:/.bbs_conan/4e258c5/1"  # spdlog.generic
    "D:/.bbs_conan/54693d2/1"  # tclap.generic
    "D:/.bbs_conan/8c7a410/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/0f0c763c7b9/1"  # tracy
)

# we have not yet defined variable
# for tag system, we shall make one
if (NOT DEFINED BRICKS_LABEL_SYSTEM_PATH)
    set(BRICKS_LABEL_SYSTEM_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_SYSTEM_PATH
    "D:/.bbs_conan/ec0e6d9f10cb3/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/da1d67082205e/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/3f54ddd49/1"  # bricks_cmake_groups.__system
)
