#Generated by D:\.bbs_conan\3f54ddd49\1\cmake\post\implicit_dependencies\generation\__init__.py; DO NOT EDIT!


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/BRIDGES_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/BRIDGES_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/BRIDGES_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/BRIDGES_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/CONTROL_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/CONTROL_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/NEXT_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/NEXT_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/PLAYER_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/PLAYER_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/SDK_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/SDK_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/SDK_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/SDK_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/UDEX_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/UDEX_COMPONENT"
)


file(
    INSTALL
        "D:/TATA/LATEST_NXT_REPO/next/conan_workarea/h/7ab8c1f1fd4e01ab32b4c38f491e59e1/.bricks/d/workdir/next/UDEX_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/UDEX_COMPONENT"
)
