
# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(Threads QUIET)
else()
    find_package(Threads)
endif()

if (NOT (Threads_FOUND))

    # depending package cannot be imported
    set(next_SDK_COMPONENT_FOUND 0)
    set(
        next_SDK_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package Threads failed: ${Threads_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(eCAL QUIET)
else()
    find_package(eCAL)
endif()

if (NOT (eCAL_FOUND))

    # depending package cannot be imported
    set(next_SDK_COMPONENT_FOUND 0)
    set(
        next_SDK_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package eCAL failed: ${eCAL_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(mts_sentinel QUIET)
else()
    find_package(mts_sentinel)
endif()

if (NOT (mts_sentinel_FOUND))

    # depending package cannot be imported
    set(next_SDK_COMPONENT_FOUND 0)
    set(
        next_SDK_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package mts_sentinel failed: ${mts_sentinel_NOT_FOUND_MESSAGE}"
    )
endif()



# Code generated by <bricks_cmake_groups>/cmake/post/implicit_dependencies/generate.py; DO NOT EDIT!

# try importing package
if (next_FIND_QUIETLY)
    find_package(spdlog QUIET)
else()
    find_package(spdlog)
endif()

if (NOT (spdlog_FOUND))

    # depending package cannot be imported
    set(next_SDK_COMPONENT_FOUND 0)
    set(
        next_SDK_COMPONENT_NOT_FOUND_MESSAGE
        "Importing required package spdlog failed: ${spdlog_NOT_FOUND_MESSAGE}"
    )
endif()

