#ifndef NEXT_APPSUPORT_CONFIG_H_
#define NEXT_APPSUPORT_CONFIG_H_

#define PROJECT_NAME "next"
#define PROJECT_VER  "0.0.0"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "0"

#endif // NEXT_APPSUPORT_CONFIG_H_
