#Generated by D:\.bbs_conan\1e3a16\1\cmake\post\implicit_dependencies\generation\__init__.py; DO NOT EDIT!


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/BRIDGES_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/BRIDGES_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/BRIDGES_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/BRIDGES_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/CONTROL_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/CONTROL_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/NEXT_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/NEXT_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/PLAYER_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/PLAYER_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/SDK_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/SDK_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/SDK_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/SDK_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/UDEX_COMPONENT/required_siblings.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/UDEX_COMPONENT"
)


file(
    INSTALL
        "D:/Next-python_API/next/conan_workarea/h/1c8ed01dedea1a0fcedaba3a730f4481/.bricks/d/workdir/next/UDEX_COMPONENT/required_packages.cmake"
    DESTINATION
        "${CMAKE_INSTALL_PREFIX}/next/share/cmake/next/UDEX_COMPONENT"
)
