
# Generated file; Do not edit!
# Generated by D:/.bbs_conan/94a71d/1/cmake/pre/scripts/tagged_paths_json_to_cmake.py
#
# This file is for Bricks core internal use only and thus
# DO NOT USE OUTSIDE BRICKS CORE!

# This file lists paths to external libraries
# which our current package uses


# we have not yet defined variable
# for tag all, we shall make one
if (NOT DEFINED BRICKS_LABEL_ALL_PATH)
    set(BRICKS_LABEL_ALL_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_ALL_PATH
    "D:/.bbs_conan/b9d1f2/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/ef297c/1"  # asio.generic
    "D:/.bbs_conan/c77abb/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/94a71d/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/1e3a16/1"  # bricks_cmake_groups.__system
    "D:/.bbs_conan/a2cb08/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/8dd44f/1"  # cip_build_system_platforms.__system
    "D:/.bbs_conan/1e35b5/1"  # cmake
    "D:/.bbs_conan/861632/1"  # ecal.measurement
    "D:/.bbs_conan/8f563d/1"  # flatbuffers
    "D:/.bbs_conan/575ef6/1"  # hdf5.generic
    "D:/.bbs_conan/f99f7b/1"  # jsoncpp.generic
    "D:/.bbs_conan/ed40e4/1"  # make
    "D:/.bbs_conan/c926df/1"  # mts-core-lib
    "D:/.bbs_conan/05150c/1"  # mts-sentinel
    "D:/.bbs_conan/0d3178/1"  # opencv.generic
    "D:/.bbs_conan/d8cf06/1"  # protobuf
    "D:/.bbs_conan/821b1a/1"  # recycle.generic
    "D:/.bbs_conan/906693/1"  # simpleini.generic
    "D:/.bbs_conan/bd8589/1"  # spdlog.generic
    "D:/.bbs_conan/d57d72/1"  # tclap.generic
    "D:/.bbs_conan/f65a98/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/962cbc/1"  # tracy
)

# we have not yet defined variable
# for tag build, we shall make one
if (NOT DEFINED BRICKS_LABEL_BUILD_PATH)
    set(BRICKS_LABEL_BUILD_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_BUILD_PATH
    "D:/.bbs_conan/b9d1f2/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/c77abb/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/94a71d/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/1e3a16/1"  # bricks_cmake_groups.__system
    "D:/.bbs_conan/a2cb08/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/8dd44f/1"  # cip_build_system_platforms.__system
    "D:/.bbs_conan/1e35b5/1"  # cmake
    "D:/.bbs_conan/8f563d/1"  # flatbuffers
    "D:/.bbs_conan/f99f7b/1"  # jsoncpp.generic
    "D:/.bbs_conan/ed40e4/1"  # make
    "D:/.bbs_conan/0d3178/1"  # opencv.generic
    "D:/.bbs_conan/d8cf06/1"  # protobuf
    "D:/.bbs_conan/bd8589/1"  # spdlog.generic
)

# we have not yet defined variable
# for tag deploy, we shall make one
if (NOT DEFINED BRICKS_LABEL_DEPLOY_PATH)
    set(BRICKS_LABEL_DEPLOY_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_DEPLOY_PATH
    "D:/.bbs_conan/ef297c/1"  # asio.generic
    "D:/.bbs_conan/861632/1"  # ecal.measurement
    "D:/.bbs_conan/575ef6/1"  # hdf5.generic
    "D:/.bbs_conan/c926df/1"  # mts-core-lib
    "D:/.bbs_conan/05150c/1"  # mts-sentinel
    "D:/.bbs_conan/821b1a/1"  # recycle.generic
    "D:/.bbs_conan/906693/1"  # simpleini.generic
    "D:/.bbs_conan/d57d72/1"  # tclap.generic
    "D:/.bbs_conan/f65a98/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/962cbc/1"  # tracy
)

# we have not yet defined variable
# for tag platform, we shall make one
if (NOT DEFINED BRICKS_LABEL_PLATFORM_PATH)
    set(BRICKS_LABEL_PLATFORM_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_PLATFORM_PATH
    "D:/.bbs_conan/8dd44f/1"  # cip_build_system_platforms.__system
)

# we have not yet defined variable
# for tag production, we shall make one
if (NOT DEFINED BRICKS_LABEL_PRODUCTION_PATH)
    set(BRICKS_LABEL_PRODUCTION_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_PRODUCTION_PATH
    "D:/.bbs_conan/b9d1f2/1"  # VFR_Utilities.generic
    "D:/.bbs_conan/ef297c/1"  # asio.generic
    "D:/.bbs_conan/a2cb08/1"  # cip_adaption_boost.generic
    "D:/.bbs_conan/1e35b5/1"  # cmake
    "D:/.bbs_conan/861632/1"  # ecal.measurement
    "D:/.bbs_conan/8f563d/1"  # flatbuffers
    "D:/.bbs_conan/575ef6/1"  # hdf5.generic
    "D:/.bbs_conan/f99f7b/1"  # jsoncpp.generic
    "D:/.bbs_conan/ed40e4/1"  # make
    "D:/.bbs_conan/c926df/1"  # mts-core-lib
    "D:/.bbs_conan/05150c/1"  # mts-sentinel
    "D:/.bbs_conan/0d3178/1"  # opencv.generic
    "D:/.bbs_conan/d8cf06/1"  # protobuf
    "D:/.bbs_conan/821b1a/1"  # recycle.generic
    "D:/.bbs_conan/906693/1"  # simpleini.generic
    "D:/.bbs_conan/bd8589/1"  # spdlog.generic
    "D:/.bbs_conan/d57d72/1"  # tclap.generic
    "D:/.bbs_conan/f65a98/1"  # tcp_pubsub.generic
    "D:/.bbs_conan/962cbc/1"  # tracy
)

# we have not yet defined variable
# for tag system, we shall make one
if (NOT DEFINED BRICKS_LABEL_SYSTEM_PATH)
    set(BRICKS_LABEL_SYSTEM_PATH)
endif()

# add paths to the listing
list(
    APPEND
    BRICKS_LABEL_SYSTEM_PATH
    "D:/.bbs_conan/c77abb/1"  # bricks_cmake_checks.__system
    "D:/.bbs_conan/94a71d/1"  # bricks_cmake_core.__system
    "D:/.bbs_conan/1e3a16/1"  # bricks_cmake_groups.__system
)
