#ifndef NEXT_INTERFACE_CONFIG_GUARD
#define NEXT_INTERFACE_CONFIG_GUARD

#define PROJECT_NAME "next"
#define PROJECT_VER  "0.0.0"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "0"

#endif // NEXT_INTERFACE_CONFIG_GUARD
